name: HAMC Server Java
description: Host a Java Minecraft server on Home Assistant
version: 1.2.2
slug: hamc-java
init: false
arch:
  - amd64
  - aarch64
  - armv7
ports:
  25565/tcp: "25565"
  25575/tcp: null
  8100/tcp: null
  8123/tcp: null
  8800/tcp: null
  8080/tcp: null
  9000/tcp: null
  30000/tcp: null
  30001/tcp: null
  31000/tcp: null
  31001/tcp: null
  19132/udp: "19132"
ports_description:
  25565/tcp: Minecraft Java Server (port principal du jeu)
  25575/tcp: RCON - Console distante d'administration
  8100/tcp: BlueMap - Carte web 3D interactive
  8123/tcp: Dynmap - Carte web 2D/3D en temps réel
  8800/tcp: Plan - Dashboard de statistiques joueurs/serveur
  8080/tcp: Interface web générique pour plugins/dashboards
  9000/tcp: Interface web alternative pour mods ou API
  30000/tcp: Port libre pour services web ou API personnalisés
  30001/tcp: Port libre alternatif pour services personnalisés
  31000/tcp: Port plugins/mods web supplémentaires
  31001/tcp: Port plugins/mods web supplémentaires alternatif
  19132/udp: Port pour bridge bedrock ( Geyser )
options:
  VERSION: LATEST
  SERVER_NAME: "HAMC Java Server"
  MOTD: "Greetings from Home Assistant"
  LEVEL: "World"
  MODE: survival
  DIFFICULTY: normal
  HARDCORE: false
  MAX_PLAYERS: 10
  WHITELIST: ""
  OPS: ""
  SPAWN_PROTECTION: 0
  PVP: true
  MAX_WORLD_SIZE: 29999984
  ALLOW_NETHER: true
  SEED: ""
  VIEW_DISTANCE: 10
  ONLINE_MODE: true
  MEMORY: 1G
  ANNOUNCE_PLAYER_ACHIEVEMENTS: true
  ENABLE_COMMAND_BLOCK: false
  FORCE_GAMEMODE: false
  MAX_BUILD_HEIGHT: 256
  TYPE: VANILLA
  RCON_PASSWORD: ""
schema:
  VERSION: str
  TYPE: list(VANILLA|FABRIC|BUKKIT|SPIGOT|FORGE|PAPER|QUILT|MAGMA|MAGMA_MAINTAINED|KETTING|MOHIST|CATSERVER)
  SERVER_NAME: str
  MOTD: str
  LEVEL: str
  MODE: list(survival|creative|adventure|spectator)
  DIFFICULTY: list(peaceful|easy|normal|hard)
  HARDCORE: bool
  MAX_PLAYERS: int
  WHITELIST: str
  OPS: str
  SPAWN_PROTECTION: int
  PVP: bool
  MAX_WORLD_SIZE: int
  ALLOW_NETHER: bool
  SEED: str
  VIEW_DISTANCE: int
  ONLINE_MODE: bool
  MEMORY: str
  ANNOUNCE_PLAYER_ACHIEVEMENTS: bool
  ENABLE_COMMAND_BLOCK: bool
  FORCE_GAMEMODE: bool
  MAX_BUILD_HEIGHT: int
  RCON_PASSWORD: password
map:
  - type: data
    read_only: false
    path: /hassio_data
  - type: addon_config
    read_only: false
    path: /data
environment:
  EULA: "TRUE"
